version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ls
      - npm i
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

# artifacts:
#   files:
#     - target/my-app-1.0-SNAPSHOT.jar
#     - appspec.yml
#   discard-paths: yes
