version: 2
jobs:
  build:
    docker:
      - image: nc30/node:11.6
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: dist/

      - run:
          name: Build
          command: 'npm run build'


  deploy:
    docker:
      - image: nc30/node:11.6
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: 'npm run build'

      - store_artifacts:
          path: dist/

      - run:
          name: Upload to S3
          command: 'aws s3 sync dist/ s3://${S3_BUCKET}/sateraito_nagoya/ --delete'

      - run:
          name: sync server
          command: 'ssh ${SYNC_USERNAME}@${SYNC_HOST} -o "StrictHostKeyChecking=no"'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - /feature\/.*/
      - deploy:
          filters:
            branches:
              only:
                - master
