version: 2
jobs:
  build:
    docker:
      - image: node:11.6-alpine
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build binary
          command: 'npm run build'

