version: 2
jobs:
  build:
    docker:
      - image: node:11.6-alpine
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: 'npm run build'

      - run:
          name: create archive
          command: zip -r latest.zip dist/*

      - store_artifacts:
          path: dist
