version: 2
jobs:
  build:
    docker:
      - image: node:11.6-alpine
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: 'npm run build'


  deploy:
    docker:
      - image: node:11.6-alpine
    environment:
      TZ: Asia/Tokyo
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Packages
          command: 'npm i'

      - run:
          name: Install Packages
          command: 'npm rebuild node-sass'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: 'npm run build'

      - run:
          name: Upload to S3
          command: 'aws s3 sync dist/ s3://${S3_BUCKET}/sateraito_nagoya/ --region ap-northeast-1 --delete'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/

      - deploy:
        filters:
          branches:
            only: master
